const START_FETCHING_DISCUSSIONS    = 'kiwi-forum/forumFeed/START_FETCHING_DISCUSSIONS';
const STOP_FETCHING_DISCUSSIONS     = 'kiwi-forum/forumFeed/STOP_FETCHING_DISCUSSIONS';
const FETCHING_DISCUSSIONS_SUCCESS  = 'kiwi-forum/forumFeed/FETCHING_DISCUSSIONS_SUCCESS';
const FETCHING_DISCUSSIONS_FAILURE  = 'kiwi-forum/forumFeed/FETCHING_DISCUSSIONS_FAILURE';
const UPDATE_SORTING_METHOD         = 'kiwi-forum/forumFeed/UPDATE_SORTING_METHOD';
const INVALID_FORUM                 = 'kiwi-forum/forumFeed/INVALID_FORUM';

export {
    START_FETCHING_DISCUSSIONS,
    STOP_FETCHING_DISCUSSIONS,
    FETCHING_DISCUSSIONS_SUCCESS,
    FETCHING_DISCUSSIONS_FAILURE,
    UPDATE_SORTING_METHOD,
    INVALID_FORUM
};
