const UPDATECURRENTFORUM        = 'kiwi-forum/app/UPDATE_CURRENT_FORUM';
const START_FETCHING_FORUMS     = 'kiwi-forum/app/START_FETCHING_FORUMS';
const STOP_FETCHING_FORUMS      = 'kiwi-forum/app/STOP_FETCHING_FORUMS';
const FETCHING_FORUMS_SUCCESS   = 'kiwi-forum/app/FETCHING_FORUMS_SUCCESS';
const FETCHING_FORUMS_FAILURE   = 'kiwi-forum/app/FETCHING_FORUMS_FAILURE';
const START_FETCHING_USER       = 'kiwi-forum/app/START_FETCHING_USER';
const FETCHING_USER_SUCCESS     = 'kiwi-forum/app/FETCHING_USER_SUCCESS';
const FETCHING_USER_FAILURE     = 'kiwi-forum/app/FETCHING_USER_FAILURE';
const SIGNOUT_USER_SUCCESS      = 'kiwi-forum/app/SIGNOUT_USER_SUCCESS';
const SIGNOUT_USER_FAILURE      = 'kiwi-forum/app/SIGNOUT_USER_FAILURE';
const UPDATE_ROOT_CLASS         = 'kiwi-forum/app/UPDATE_ROOT_CLASS';
const OPEN_COMPOSER             = 'kiwi-forum/app/OPEN_COMPOSER';
const CLOSE_COMPOSER            = 'kiwi-forum/app/CLOSE_COMPOSER';

export {
    UPDATECURRENTFORUM,
    START_FETCHING_FORUMS,
    STOP_FETCHING_FORUMS,
    FETCHING_FORUMS_SUCCESS,
    FETCHING_FORUMS_FAILURE,
    START_FETCHING_USER,
    FETCHING_USER_SUCCESS,
    FETCHING_USER_FAILURE,
    SIGNOUT_USER_SUCCESS,
    SIGNOUT_USER_FAILURE,
    UPDATE_ROOT_CLASS,
    OPEN_COMPOSER,
    CLOSE_COMPOSER
};
