const UPDATECURRENTTAGS         = 'kiwi-forum/app/UPDATE_CURRENT_TAGS';
const START_FETCHING_TAGS       = 'kiwi-forum/app/START_FETCHING_TAGS';
const STOP_FETCHING_TAGS        = 'kiwi-forum/app/STOP_FETCHING_TAGS';
const FETCHING_TAGS_SUCCESS     = 'kiwi-forum/app/FETCHING_TAGS_SUCCESS';
const FETCHING_TAGS_FAILURE     = 'kiwi-forum/app/FETCHING_TAGS_FAILURE';
const START_FETCHING_USER       = 'kiwi-forum/app/START_FETCHING_USER';
const FETCHING_USER_SUCCESS     = 'kiwi-forum/app/FETCHING_USER_SUCCESS';
const FETCHING_USER_FAILURE     = 'kiwi-forum/app/FETCHING_USER_FAILURE';
const SIGNOUT_USER_SUCCESS      = 'kiwi-forum/app/SIGNOUT_USER_SUCCESS';
const SIGNOUT_USER_FAILURE      = 'kiwi-forum/app/SIGNOUT_USER_FAILURE';
const UPDATE_ROOT_CLASS         = 'kiwi-forum/app/UPDATE_ROOT_CLASS';
const OPEN_COMPOSER             = 'kiwi-forum/app/OPEN_COMPOSER';
const CLOSE_COMPOSER            = 'kiwi-forum/app/CLOSE_COMPOSER';

export {
    UPDATECURRENTTAGS,
    START_FETCHING_TAGS,
    STOP_FETCHING_TAGS,
    FETCHING_TAGS_SUCCESS,
    FETCHING_TAGS_FAILURE,
    START_FETCHING_USER,
    FETCHING_USER_SUCCESS,
    FETCHING_USER_FAILURE,
    SIGNOUT_USER_SUCCESS,
    SIGNOUT_USER_FAILURE,
    UPDATE_ROOT_CLASS,
    OPEN_COMPOSER,
    CLOSE_COMPOSER
};
